services:
  - type: web
    name: face-swap-backend
    runtime: python
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg libsm6 libxext6 libxrender-dev libgomp1 libglib2.0-0 libgl1
      pip install --no-cache-dir -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 7860
    healthCheckPath: /
    plan: free
